env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends: 'airbnb'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
parser: 'babel-eslint'
plugins:
  - react
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - always
